### ISSUE TITLE
getting error: Plugin details file failed validation

### ISSUE THREAD

**Issue by chithambarams** [alexcurtis/contactform-pencilblue#3]
getting Errors:
An invalid main module path and/or file was provided.
while installing the module..Please give me a solution. I'm new to node....

**Comment by janpetras** [comment]
I'm getting the same error. I closely followed all the installation instructions but I get the same error.

I cloned this repo, I restarted pencilblue, I went to the admin/plugins section, but I have no install button, only an error message like the one above. What's up?

**Comment by alexcurtis** [comment]
@chithambarams @janpetras There were some breaking changes made in PencilBlue 0.4.x. I'll update the plugin to be compatible with the latest version.

**Comment by janpetras** [comment]
That would be awesome. I'm currently using the basic contact form from Pencilblue and I love the submitted data being saved as custom objects but it lacks the emailer service.

Yours would fix the emailer service issues! I tried to fix it and initially I thought it's only the removal of the PluginService (and replacing it with the 'pb' global) but I think there are more things that broke so I'll continue to poke around for a bit but I'm not very experienced.

**Comment by greergan** [comment]
Just curios if there are any updates for this issue yet?

Cheers.

**Comment by alexcurtis** [comment]
@greergan Sorry for the delay. I'll get this sorted as soon as possible. Thank you for your patience.

**Comment by greergan** [comment]
thank you

**Comment by alexcurtis** [comment]
@chithambarams @greergan @greergan Hi Guys. I have pushed a long delayed update to master, that includes support for Pencil Blue 0.4.x. Please could you try it out and let me know if there are any issues. Sorry again for the delay.
