### ISSUE TITLE
Getting error adding contact form to template

### ISSUE THREAD

**Issue by Chris-Satchell** [alexcurtis/contactform-pencilblue#4]
So I followed your instructions, but when I add ^tmp_contact_form^ to the template, all I get is this:

![Image of Issue](http://puu.sh/liMqx/e5f95878d6.png)

Am I missing something obvious? Still pretty new to PB

**Comment by alexcurtis** [comment]
@Chris-Satchell Looks like it isn't using the css file. Are you doing anything special with the theme settings?

**Comment by Chris-Satchell** [comment]
@alexcurtis I´m on PB 0.4.1 and you´re right, I´m currently developing a new theme for a website. It was indeed not loading the CSS file and as I moved all the JS stuff to the footer, it also couldn´t find JQuery. Solved and working nicely, thanks for a great plugin

**Comment by alexcurtis** [comment]
@Chris-Satchell Awesome. Thanks Chris!
